// Common words for frequency analysis
export const commonWords = new Set([
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "i",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
]);

// AI-typical phrases and patterns (expanded)
export const aiPatterns = [
  /\b(it is important to note|it should be noted|it is worth mentioning|it is crucial to understand)\b/gi,
  /\b(furthermore|moreover|additionally|consequently|therefore|thus|hence|nonetheless|nevertheless)\b/gi,
  /\b(in conclusion|to summarize|in summary|overall|ultimately|essentially)\b/gi,
  /\b(various|numerous|several|multiple|different|diverse|wide range of)\b/gi,
  /\b(enhance|optimize|facilitate|utilize|implement|establish|maintain|ensure)\b/gi,
  /\b(significant|substantial|considerable|notable|remarkable|extensive)\b/gi,
  /\b(comprehensive|thorough|detailed|in-depth|multifaceted)\b/gi,
  /\b(approach|strategy|methodology|framework|process|procedure)\b/gi,
  // New AI patterns based on recent models
  /\b(it's worth noting|it's important to understand|it's crucial to consider)\b/gi,
  /\b(as we delve into|let's explore|let's examine|it's clear that)\b/gi,
  /\b(in today's|in our modern|in the current|in this digital age)\b/gi,
  /\b(revolutionize|transform|streamline|cutting-edge|state-of-the-art)\b/gi,
  /\b(stakeholders|end-users|best practices|value proposition|synergistic)\b/gi,
  /\b(leverage the power of|harness the potential|unlock the benefits)\b/gi,
];

// Human-like patterns and indicators
export const humanPatterns = [
  /\b(lol|lmao|omg|wtf|btw|tbh|imho|imo)\b/gi,
  /\b(gonna|wanna|gotta|kinda|sorta|dunno)\b/gi,
  /\b(yeah|yep|nah|nope|meh|ugh|hmm)\b/gi,
  /\b(super|really|pretty|kinda|totally|absolutely)\b/gi,
  /\b(awesome|amazing|terrible|awful|weird|crazy)\b/gi,
];

// Emotional expressions
export const emotionalMarkers = [
  /\b(love|hate|excited|frustrated|angry|happy|sad|worried|anxious)\b/gi,
  /\b(feel|felt|feeling|emotions|emotional|mood)\b/gi,
  /(!{2,}|\?{2,}|\.{3,})/g, // Multiple punctuation marks
  /[A-Z]{2,}/g, // CAPS for emphasis
];

// Discourse markers for sophisticated analysis
export const discourseMarkers = [
  "first",
  "second",
  "third",
  "finally",
  "lastly",
  "initially",
  "subsequently",
  "meanwhile",
  "simultaneously",
  "on the other hand",
  "in contrast",
  "however",
  "nevertheless",
  "for instance",
  "for example",
  "such as",
  "namely",
  "in fact",
  "indeed",
  "actually",
  "certainly",
  "admittedly",
  "granted",
  "of course",
  "naturally",
];

// Function words for stylometric analysis
export const functionWords = [
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "i",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
];

// Transition words for density analysis
export const transitionWords = [
  "however",
  "furthermore",
  "moreover",
  "additionally",
  "consequently",
  "therefore",
  "thus",
  "hence",
  "nevertheless",
  "nonetheless",
  "meanwhile",
  "subsequently",
  "ultimately",
  "essentially",
  "specifically",
  "particularly",
  "notably",
  "importantly",
  "significantly",
  "interestingly",
  "surprisingly",
  "accordingly",
  "alternatively",
  "comparatively",
  "conversely",
  "similarly",
  "likewise",
  "meanwhile",
  "simultaneously",
];

// Sophisticated vocabulary often used by AI
export const sophisticatedWords = [
  "utilize",
  "facilitate",
  "demonstrate",
  "implement",
  "establish",
  "maintain",
  "require",
  "appropriate",
  "significant",
  "considerable",
  "substantial",
  "comprehensive",
  "extensive",
  "innovative",
  "strategic",
  "optimize",
  "enhance",
  "leverage",
  "paradigm",
  "methodology",
  "framework",
  "initiative",
  "synergy",
];
